apiVersion: v1
kind: Service
metadata:
  name: ragmgmt
  namespace: rhc-rag
  labels:
    app.kubernetes.io/name: ragmgmt-service
    app.kubernetes.io/part-of: regulated-healthcare-rag
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ragmgmt-service
  ports:
    - name: http
      port: 8002
      targetPort: http
      protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ragmgmt
  namespace: rhc-rag
  labels:
    app.kubernetes.io/name: ragmgmt-service
    app.kubernetes.io/part-of: regulated-healthcare-rag
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ragmgmt
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
